#424: Allow Drupal 10
itk-dev/azure-ad-delta-sync-drupal pull request #6
Opened 2024-02-07 11:55 UTC by jekuaitk

https://leantime.itkdev.dk/#/tickets/showTicket/424

2025-01-28 09:10 UTC, rimi-itk requested changes
Good work. Some changed are needed to make it even better.

2025-01-28 09:10 UTC, rimi-itk commented on README.md
> +$config['azure_ad_delta_sync.settings']['azure']['tenant_id'] = '…';
Are these settings still needed? What do we use `tenant_id` and `group_id` for?

2025-01-28 09:10 UTC, rimi-itk commented on README.md
> +php «DRUPAL_ROOT»/web/core/scripts/generate-proxy-class.php 'Drupal\azure_ad_delta_sync\Controller' web/modules/contrib/azure_ad_delta_sync_drupal/src
We should add a GitHub Action to check that the proxy classes are up-to-date, e.g. by adding a script (similar to `code-analysis`) that can update the classes.

2025-01-28 09:10 UTC, rimi-itk commented on README.md
> +docker run --rm --volume "$PWD:/md" peterdavehello/markdownlint markdownlint '**/*.md' --fix
I think we should apply coding standards before checking them:

```suggestion
docker run --rm --volume "$PWD:/md" peterdavehello/markdownlint markdownlint '**/*.md' --fix
docker run --rm --volume "$PWD:/md" peterdavehello/markdownlint markdownlint '**/*.md'
```

2025-01-28 09:10 UTC, rimi-itk commented on README.md
> +./scripts/code-analysis
We should run this with docker, e.g. like it's done in <https://github.com/itk-dev/getorganized-api-client-php?tab=readme-ov-file#code-analysis>.

2025-01-28 09:10 UTC, rimi-itk commented on composer.json
> +        "mglaman/drupal-check": "^1.4",
Do we still use this? Or do we use PHPStan with some custom configuration?

2025-01-28 09:10 UTC, rimi-itk commented on composer.json
> +          ],
Are these superseded by `./scripts/code-analysis`?

2025-01-28 09:10 UTC, rimi-itk commented on phpstan.neon
> +  level: 0
Consider bumping the level to 5 or 6 (cf. https://phpstan.org/user-guide/rule-levels). Level 0 is very basic.

2025-01-28 09:10 UTC, rimi-itk commented on phpstan.neon
> +      - vendor
Consider telling your text editor to add a newline at end of files when saving.

2025-01-28 09:10 UTC, rimi-itk commented on src/UserManager.php
>              $query->condition($orCondition);
We should add the or condition only it it's not empty, e.g. by adding it inside the `if (NULL !== $providerUserIdQuery) {` block.

2025-01-28 09:10 UTC, rimi-itk commented on src/UserManager.php
> +    // to log in. All of the content will remain attributed to the username.
🎉

2025-01-28 09:10 UTC, rimi-itk commented on src/UserManager.php
> +      case 'openid_connect.generic':
User providers (e.g. for OpenID Connect) are defined in configuration (e.g. https://github.com/itk-dev/hoeringsportal/blob/develop/config/sync/openid_connect.client.generic.yml), so we need to refactor this function completely to take that into consideration.

2025-01-28 09:10 UTC, rimi-itk commented on src/UserManager.php
> +      $this->cacheUserIdsForDeletion($userIds);
We should not use a cache for storing the user IDs. Just using a variable will suffice, and using a cache may not work as expected, e.g. if somebody clears the cache while we're running.

2025-01-28 09:10 UTC, rimi-itk commented on src/Form/SettingsForm.php
> +    $options = ['openid_connect.generic' => $this->t('OpenId Connect')];
OpenID Connect providers are defined in config (and more and others than “generic”), so we need to get this list by finding all providers configured. It may make sense to extend the user manager to be able to provide a list of all user providers in the system.

2025-01-28 09:36 UTC, sinejespersen commented on src/UserManager.php
> +      $this->cacheUserIdsForDeletion($userIds);
Roger

2025-01-28 10:03 UTC, sinejespersen commented on README.md
> +$config['azure_ad_delta_sync.settings']['azure']['tenant_id'] = '…';
remoooved

2025-01-28 10:03 UTC, sinejespersen commented on README.md
> +$config['azure_ad_delta_sync.settings']['azure']['tenant_id'] = '…';
or replaced actually

2025-01-28 13:34 UTC, sinejespersen commented on phpstan.neon
> +  level: 0
Why 5 or 6?

2025-01-30 09:04 UTC, rimi-itk requested changes

2025-01-30 09:04 UTC, rimi-itk commented on README.md
> +Requires a full Drupal installation with the `azure_ad_delta_sync_drupal` module in the
The module's machine name is “azure_ad_delta_sync” (cf. `azure_ad_delta_sync_drupal.info.yml`):

```suggestion
Requires a full Drupal installation with the `azure_ad_delta_sync` module in the
```

2025-01-30 09:04 UTC, rimi-itk commented on README.md
> +(cd «DRUPAL_ROOT»/web; ./vendor/bin/phpunit modules/contrib/azure_ad_delta_sync_drupal/tests/src/Functional)
```suggestion
(cd «DRUPAL_ROOT»/web; ./vendor/bin/phpunit modules/contrib/azure_ad_delta_sync/tests/src/Functional)
```

2025-01-30 09:04 UTC, rimi-itk commented on README.md
> +docker run --rm --volume "$PWD:/md" peterdavehello/markdownlint markdownlint '**/*.md' --fix
https://github.com/PeterDaveHello is cool!

2025-01-30 09:04 UTC, rimi-itk commented on azure_ad_delta_sync.services.yml
> +      - '@request_stack'
Note to self: We should autowire services in a (near) future pull request (cf. https://www.drupal.org/node/3284600).

2025-01-30 09:04 UTC, rimi-itk commented on composer.json
>          "itk-dev/drupal_psr6_cache": "^1.0",
Remove the dependency on itk-dev/drupal_psr6_cache.

2025-01-30 09:04 UTC, rimi-itk commented on src/Drush/Commands/Commands.php
> +    }
Consider moving this check to right after line 55.

2025-01-30 09:04 UTC, rimi-itk commented on src/Form/SettingsForm.php
> +  public static function create(ContainerInterface $container): SettingsForm {
Consider using `static` as return type. 

```suggestion
  public static function create(ContainerInterface $container): static {
```

It doesn't change anything right nok, but it's easier to always write

```
  public static function create(ContainerInterface $container): static {
```

than

```
  public static function create(ContainerInterface $container): WhateverClassNameWereInside {
```

https://wiki.php.net/rfc/static_return_type

2025-01-30 09:04 UTC, rimi-itk commented on src/UserManager.php
> +    // Stolen from here: https://git.drupalcode.org/project/openid_connect/-/blob/3.x/src/Form/OpenIDConnectLoginForm.php?ref_type=heads#L78
🎉

2025-01-30 09:04 UTC, rimi-itk commented on src/UserManager.php
> +    }
I think we should skip the check:

```suggestion
    $this->userIds = $managedUserIds;
    $this->logger->info($this->formatPlural(
      count($this->userIds),
      '1 user marked for deletion.',
      '@count users marked for deletion.'
    ));
```

If we don't reset the list (even when it's empty), we can risk reusing a non-empty list and delete too many users. It's theoretical and unlikely, but I still think we always user the actual list of managed user IDs.

2025-01-30 09:04 UTC, rimi-itk commented on src/UserManager.php
> +  private $userIds;
Add types:

```
   * @var array|int[]
   */
  private array $userIds;
```

2025-01-30 09:04 UTC, rimi-itk commented on src/UserManager.php
> +    if (is_array($this->userIds)) {
If you add a type to `$userIds` (cf. comment on `$userIds`) you can skip this check.

2025-01-30 09:04 UTC, rimi-itk commented on src/UserManager.php
> +        }
The empty list is also a list:

```suggestion
    $this->logger->info($this->formatPlural(
      count($deletedUserIds),
      'One user to be deleted',
      '@count users to be deleted'
    ));
    if ($this->options['debug'] ?? FALSE) {
      $users = $this->userStorage->loadMultiple($deletedUserIds);
      foreach ($users as $user) {
        $this->logger->debug(sprintf('User to be deleted: %s (#%s)', $user->label(), $user->id()));
      }
```

2025-01-30 09:04 UTC, rimi-itk commented on src/Form/SettingsForm.php
> +  }
This function is closely related to UserManager::unescapeProviderId. Mention this relationship in both functions' documentation. It may even be a good idea to put them right next to each other in a `ConfigHelper` class, say, (or the UserManager for pragmatic reasons) and add additional `setConfiguration(string, array)` and `getConfiguration(string)` helper functions that escape and unescape config keys as needed.

2025-01-30 09:04 UTC, rimi-itk commented on Dockerfile
> +USER deploy
See https://stackoverflow.com/a/44704969 (and https://stackoverflow.com/questions/729692/why-should-text-files-end-with-a-newline if you're really curious).

2025-01-30 09:04 UTC, rimi-itk commented on src/Form/SettingsForm.php
> +    }
We should rename the UserManager's `getActiveOpenIdConnectProviders` function to `getAllUserProviders`, say, since we should not only care about OpenID Connect providers. We currently use only OIDC, but writing generic code is often easier than writing code for specific use cases.

`UserManager::getAllUserProviders` can take care of escaping config keys, or we can add a `getAllUserProvidersAsConfigOptions` to be more explicit.

2025-01-30 09:12 UTC, sinejespersen commented on composer.json
>          "itk-dev/drupal_psr6_cache": "^1.0",
jeps

2025-01-30 09:41 UTC, sinejespersen commented on src/UserManager.php
> +    }
Why skip the count?

2025-01-30 09:48 UTC, rimi-itk commented on src/UserManager.php
> +    }
Because we must always process the list even when it's empty. It will probably never be empty, but assume this (contrived) example:

1. We run delta sync and are told to delete user 2
2. User 2 is now deleted
3. We run delta sync again and are told to delete no users (since user 2 is already deleted), but if we only process non-empty lists, we will reuse the list containing user 2

2025-01-30 09:51 UTC, sinejespersen commented on src/Form/SettingsForm.php
> +  }
will do

2025-01-30 10:26 UTC, sinejespersen commented on Dockerfile
> +USER deploy
done

2025-01-31 10:03 UTC, sinejespersen commented on src/Helpers/ConfigHelper.php
> +   * @todo talk to Mikkel about this
remember this @sinejespersen @rimi-itk

2025-02-03 08:59 UTC, rimi-itk reviewed
Looks good. Some minor adjustments can make it even better – and done.

We need to clean up the way we use the logger. We should pass static strings to `log` and use placeholders for dynamic values (cf. https://drupalize.me/blog/how-log-messages-drupal-8). We'll do that in another pull request to keep things clean.

2025-02-03 08:59 UTC, rimi-itk commented on src/Form/SettingsForm.php
> +  public function __construct(ConfigFactoryInterface $configFactory, EntityTypeManager $entityTypeManager, UserManagerInterface $userManager, ConfigHelper $configHelper) {
You can use https://www.php.net/manual/en/language.oop5.decon.php#language.oop5.decon.constructor.promotion to define `$configHelper`:

```suggestion
  public function __construct(ConfigFactoryInterface $configFactory, EntityTypeManager $entityTypeManager, UserManagerInterface $userManager, private ConfigHelper $configHelper) {
```

(and remove the declaration in line 45 and also remove line 67).

2025-02-03 08:59 UTC, rimi-itk commented on src/Helpers/ConfigHelper.php
> +    // https://www.drupal.org/node/2297311
🎉

2025-02-03 08:59 UTC, rimi-itk commented on src/Form/SettingsForm.php
> +    $options = $this->configHelper->getAllUserProviders();
For consistence and symmetry, we should probably use the config helper to save the config in `submitForm`.

2025-02-03 09:32 UTC, rimi-itk approved these changes

2025-02-03 09:32 UTC, merged